# SPDX-FileCopyrightText: The endjine authors
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

# Same as file name.
name: build-cli

env:
  # Disable incremental compilation for faster from-scratch builds.
  CARGO_INCREMENTAL: 0
  # Disable debug info to improve cache efficiency.
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

on:
  push:
    tags:
      - v*
  # Build release periodically to ensure that `main` remains intact.
  schedule:
    # Weekly, i.e. on Monday at 04:30 UTC
    - cron: "30 4 * * 1"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Let side effects of existing run finish.
  cancel-in-progress: false

jobs:
  run:
    # Workaround for issue <https://github.com/orgs/community/discussions/16109>.
    if: (github.repository == 'uklotzde/endjine') || (github.event_name != 'schedule')

    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            runner_os: macos-latest
            cli_arch: macos-arm64
          - target: aarch64-pc-windows-msvc
            runner_os: windows-latest
            cli_arch: windows-arm64
          - target: aarch64-unknown-linux-musl
            runner_os: ubuntu-latest
            cli_arch: linux-arm64
          - target: armv7-unknown-linux-musleabihf
            runner_os: ubuntu-latest
            cli_arch: linux-armv7
          - target: x86_64-pc-windows-msvc
            runner_os: windows-latest
            cli_arch: windows-amd64
          - target: x86_64-unknown-linux-musl
            runner_os: ubuntu-latest
            cli_arch: linux-amd64

    runs-on: ${{ matrix.runner_os }}

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          # The build target will be selected implicitly by setup-cross-toolchain-action (see below).
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          # Setting the target sets the `CARGO_BUILD_TARGET` environment variable,
          # so there is no need for an explicit `--target` flag in each build step.
          # This is required for both native and cross-platform builds to avoid
          # using the default target of the runner.
          target: ${{ matrix.target }}

      # Check out the repository before the remaining steps that depend on it.
      # All preceding steps are independent of the repository contents.
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # The cache should not be shared between different workflows and jobs.
          # Use separate cache per target so that faster runner does not get exclusive cache.
          shared-key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.target }}

      - name: Build binary in release mode with default features enabled
        # YAML folded style `>` to split _single_ command into multiple lines.
        run: >-
          cargo build --locked
          -p endjine-cli
          --profile release

      - name: Prepare release artifact (*nix)
        if: ${{ !startsWith(matrix.runner_os, 'windows') }}
        # Expect explicit path to folder in `target/`, because target was named by cross-compilation
        # tool-chain.
        run: |-
          zip endjine-cli-${{ matrix.cli_arch }}.zip target/${{ matrix.target }}/release/endjine

      - name: Prepare release artifact (Windows)
        if: startsWith(matrix.runner_os, 'windows')
        # Expect explicit path to folder in `target/`, because target was named by cross-compilation
        # tool-chain.
        run: |-
          7z a endjine-cli-${{ matrix.cli_arch }}.zip target/${{ matrix.target }}/release/endjine.exe

      - name: Upload CLI artifact
        uses: actions/upload-artifact@v6
        with:
          name: CLI (${{ matrix.cli_arch }})
          path: endjine-cli-${{ matrix.cli_arch }}.zip
          if-no-files-found: error
          retention-days: 30
