# SPDX-FileCopyrightText: The endjine authors
# SPDX-License-Identifier: CC0-1.0

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

# Same as file name.
name: test

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  # Disable incremental compilation for faster from-scratch builds.
  CARGO_INCREMENTAL: 0
  # Disable debug info to improve cache efficiency.
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: short

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  run:
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            runner_os: macos-latest
          - target: aarch64-pc-windows-msvc
            runner_os: windows-latest
          - target: aarch64-unknown-linux-musl
            runner_os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            runner_os: ubuntu-latest
          - target: x86_64-pc-windows-msvc
            runner_os: windows-latest
          - target: x86_64-unknown-linux-gnu
            runner_os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            runner_os: ubuntu-latest

    runs-on: ${{ matrix.runner_os }}

    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          # The build target will be selected implicitly by setup-cross-toolchain-action (see below).
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          # Setting the target sets the `CARGO_BUILD_TARGET` environment variable,
          # so there is no need for an explicit `--target` flag in each build step.
          # This is required for both native and cross-platform builds to avoid
          # using the default target of the runner.
          target: ${{ matrix.target }}

      - name: Check out repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # The cache should not be shared between different workflows and jobs.
          # Use separate cache per target so that faster runner does not get exclusive cache.
          shared-key: ${{ github.workflow }}-${{ github.job }}-${{ matrix.target }}

      - name: Run tests
        if: matrix.target != 'aarch64-pc-windows-msvc'
        run: cargo test --locked --workspace --all-features
